ALTER TABLE estado
   ADD nome VARCHAR(50) NOT NULL;


INSERT INTO estado (codigo, nome, sigla) VALUES (1,'Ceará', 'CE');


INSERT INTO cidade (nome, codigo_estado) VALUES ('Abaiara', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Acarape', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Acaraú', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Acopiara', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Aiuaba', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Alcântaras', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Altaneira', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Alto Santo', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Amontada', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Apuiarés', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Aquiraz', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Aracati', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Aracoiaba', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Ararendá', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Araripe', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Aratuba', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Arneiroz', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Assaré', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Aurora', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Banabuiú', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Barbalha', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Barreira', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Barro', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Barroquinha', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Baturité', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Beberibe', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Bela Cruz', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Boa Viagem', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Brejo Santo', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Camocim', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Campos Sales', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Canindé', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Capistrano', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Caridade', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Cariré', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Caririaçu', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Carnaubal', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Cascavel', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Catarina', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Catunda', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Caucaia', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Chaval', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Choró', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Chorozinho', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Coreaú', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Crateús', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Crato', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Croatá', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Cruz', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Deputado Irapuan Pinheiro', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Ererê', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Eusébio', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Farias Brito', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Forquilha', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Fortaleza', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Fortim', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Frecheirinha', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('General Sampaio', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Graça', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Granja', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Granjeiro', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Groaíras', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Guaiúba', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Guaraciaba do Norte', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Guaramiranga', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Hidrolândia', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Horizonte', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Ibaretama', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Ibiapina', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Ibicuitinga', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Icapuí', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Independência', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Ipaporanga', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Ipu', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Ipueiras', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Iracema', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Irauçuba', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Itaiçaba', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Itaitinga', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Itapajé', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Itapipoca', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Itapiúna', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Itarema', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Itatira', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Jaguaretama', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Jaguaribara', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Jaguaribe', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Jaguaruana', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Jardim', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Jati', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Jijoca de Jericoacoara', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Juazeiro do Norte', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Limoeiro do Norte', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Madalena', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Maracanaú', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Maranguape', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Marco', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Martinópole', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Massapê', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Mauriti', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Meruoca', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Milagres', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Milhã', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Miraíma', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Missão Velha', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Mombaça', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Monsenhor Tabosa', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Morada Nova', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Moraújo', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Morrinhos', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Mucambo', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Mulungu', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Nova Olinda', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Nova Russas', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Novo Oriente', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Ocara', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Orós', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Pacajus', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Pacatuba', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Pacoti', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Pacujá', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Palhano', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Palmácia', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Paracuru', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Paraipaba', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Parambu', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Paramoti', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Pedra Branca', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Penaforte', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Pentecoste', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Pereiro', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Pindoretama', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Piquet Carneiro', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Pires Ferreira', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Poranga', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Porteiras', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Potengi', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Potiretama', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Quiterianópolis', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Quixadá', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Quixeramobim', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Quixeré', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Redenção', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Reriutaba', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Russas', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Saboeiro', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Salitre', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Santa Quitéria', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Santana do Acaraú', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Santana do Cariri', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('São Benedito', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('São Gonçalo do Amarante', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('São João do Jaguaribe', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('São Luís do Curu', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Senador Pompeu', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Senador Sá', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Sobral', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Solonópole', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Tabuleiro do Norte', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Tamboril', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Tauá', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Tejuçuoca', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Tianguá', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Trairi', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Tururu', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Ubajara', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Umirim', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Uruburetama', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Uruoca', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Varjota', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Várzea Alegre', 1);
INSERT INTO cidade (nome, codigo_estado) VALUES ('Viçosa do Ceará', 1);